/*drop VIEW V_SPIELTAG;*/

CREATE VIEW V_SPIELTAG as
select SPIEL.DATUM, TEAM1.NAME as "Team 1", TEAM2.NAME as "Team 2", SPIEL.TOR_TEAM1 as "Tor 1", SPIEL.TOR_TEAM2 as "Tor 2" , RUNDE.NAME as "Runde", SCHIRI.VORNAME ||" "|| SCHIRI.NAME as "Schiedsrichter", STADION.NAME as "Stadion Bezeichnung"
FROM SPIEL
inner join TEAM AS TEAM1 on (TEAM1.TEAM_ID = SPIEL.TEAM1_ID)
inner join TEAM AS TEAM2 on (TEAM2.TEAM_ID = SPIEL.TEAM2_ID)
inner join STADION on (STADION.STADION_ID = SPIEL.STADION_ID)
inner join SCHIRI on (SCHIRI.SCHIRI_ID = SPIEL.SCHIRI_ID)
inner join RUNDE on (RUNDE.RUNDE_ID = SPIEL.RUNDE_ID)
order by SPIEL.DATUM;