drop table SPIELER;

CREATE TABLE SPIELER ( 
	SPIELER_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	TEAM_ID int NOT NULL, 
	VORNAME char NOT NULL, 
	NAME char NOT NULL,
	TORE_GESAMT int NOT NULL default 0, 
	GELBE_KARTEN int NOT NULL default 0, 
	ROTE_KARTEN int NOT NULL default 0, 
	CONSTRAINT FK_TEAM_ID FOREIGN KEY(TEAM_ID) REFERENCES TEAM(TEAM_ID) 
);

INSERT INTO SPIELER (TEAM_ID, VORNAME, NAME)
VALUES
(1,"Emma", "Smith"),
(1,"Liam", "Johnson"),
(1,"Noah", "Williams"),
(1,"Olivia", "Jones"),
(1,"Ava", "Brown"),
(1,"Isabella", "Davis"),
(1,"Sophia", "Miller"),
(1,"Mia", "Wilson"),
(1,"Charlotte", "Anderson"),
(1,"Amelia", "Thomas"),

(2,"Evelyn", "Jackson"),
(2,"Abigail", "White"),
(2,"Harper", "Harris"),
(2,"Ella", "Martin"),
(2,"Avery", "Thompson"),
(2,"Mila", "Young"),
(2,"Evelyn", "Allen"),
(2,"Aria", "King"),
(2,"Scarlett", "Wright"),
(2,"Camila", "Clark"),

(3,"Aurora", "Robinson"),
(3,"Violet", "Taylor"),
(3,"Sadie", "Green"),
(3,"Natalie", "Hall"),
(3,"Addison", "Adams"),
(3,"Arianna", "Nelson"),
(3,"Makayla", "Carter"),
(3,"Aubree", "Mitchell"),
(3,"Ryleigh", "Perez"),
(3,"Brooklyn", "Roberts"),

(4,"Ellie", "Turner"),
(4,"Nora", "Phillips"),
(4,"Adalynn", "Campbell"),
(4,"Caroline", "Parker"),
(4,"Aaliyah", "Evans"),
(4,"Kaylee", "Edwards"),
(4,"Anna", "Collins"),
(4,"Aubrey", "Stewart"),
(4,"Audrey", "Sanchez"),
(4,"Aurora", "Morris"),

(5,"Autumn", "Rogers"),
(5,"Brooklynn", "Reed"),
(5,"Bella", "Cook"),
(5,"Brielle", "Bailey"),
(5,"Adalyn", "Bell"),
(5,"Avery", "Cooper"),
(5,"Aria", "Richardson"),
(5,"Avery", "Cox"),
(5,"Aubree", "Howard"),
(5,"Adalynn", "Ward"),

(6,"Aaliyah", "Torres"),
(6,"Natalie", "Peterson"),
(6,"Caroline", "Gray"),
(6,"Aurora", "Ramirez"),
(6,"Bella", "James"),
(6,"Brielle", "Watson"),
(6,"Audrey", "Brooks"),
(6,"Avery", "Kelly"),
(6,"Aurora", "Price"),
(6,"Autumn", "Bennett"),

(7,"Aria", "Wood"),
(7,"Adalyn", "Barnes"),
(7,"Aaliyah", "Ross"),
(7,"Anna", "Henderson"),
(7,"Aubrey", "Coleman"),
(7,"Adalynn", "Jenkins"),
(7,"Caroline", "Perry"),
(7,"Aurora", "Powell"),
(7,"Bella", "Long"),
(7,"Brielle", "Patterson"),

(8,"Audrey", "Hughes"),
(8,"Avery", "Flores"),
(8,"Aurora", "Washington"),
(8,"Autumn", "Butler"),
(8,"Aria", "Simmons"),
(8,"Adalyn", "Foster"),
(8,"Logan", "Williams"),
(8,"Elijah", "Jones"),
(8,"Mason", "Brown"),
(8,"James", "Davis"),

(9,"Oliver", "Miller"),
(9,"William", "Wilson"),
(9,"Benjamin", "Anderson"),
(9,"Lucas", "Thomas"),
(9,"Michael", "Jackson"),
(9,"Alexander", "White"),
(9,"Ethan", "Harris"),
(9,"Daniel", "Martin"),
(9,"Matthew", "Thompson"),
(9,"Aiden", "Young"),

(10,"Henry", "Allen"),
(10,"Owen", "King"),
(10,"Jackson", "Wright"),
(10,"Eli", "Clark"),
(10,"Wyatt", "Robinson"),
(10,"Nathan", "Taylor"),
(10,"Caleb", "Green"),
(10,"Landon", "Hall"),
(10,"Isaac", "Adams"),
(10,"Gavin", "Nelson"),

(11,"Brayden", "Carter"),
(11,"Jayden", "Mitchell"),
(11,"Natalie", "Perez"),
(11,"Miles", "Roberts"),
(11,"Jordan", "Turner"),
(11,"Evan", "Phillips"),
(11,"Luke", "Campbell"),
(11,"Jack", "Parker"),
(11,"Levi", "Evans"),
(11,"Isaiah", "Edwards"),

(12,"Grayson", "Collins"),
(12,"David", "Stewart"),
(12,"Jonathan", "Sanchez"),
(12,"Samuel", "Morris"),
(12,"Noah", "Rogers"),
(12,"Carter", "Reed"),
(12,"Aubrey", "Cook"),
(12,"Julian", "Bailey"),
(12,"John", "Bell"),
(12,"Oscar", "Cooper"),

(13,"Miles", "Richardson"),
(13,"Sebastian", "Cox"),
(13,"Levi", "Howard"),
(13,"Easton", "Ward"),
(13,"Jaxon", "Torres"),
(13,"Lincoln", "Peterson"),
(13,"Ezra", "Gray"),
(13,"Maddox", "Ramirez"),
(13,"Josiah", "James"),
(13,"Colton", "Watson"),

(14,"Braylon", "Brooks"),
(14,"Damian", "Kelly"),
(14,"Camden", "Price"),
(14,"Jace", "Bennett"),
(14,"Maverick", "Wood"),
(14,"Kai", "Barnes"),
(14,"Lincoln", "Ross"),
(14,"Jase", "Henderson"),
(14,"Caden", "Coleman"),
(14,"Miles", "Jenkins"),

(15,"Nash", "Perry"),
(15,"Asher", "Powell"),
(15,"Abigail", "Clark"),
(15,"Emily", "Lewis"),
(15,"Madison", "Robinson"),
(15,"Elizabeth", "Walker"),
(15,"Avery", "Hall"),
(15,"Ella", "Allen"),
(15,"Aubree", "King"),
(15,"Addison", "Wright"),

(16,"Aria", "Scott"),
(16,"Mila", "Green"),
(16,"Natalie", "Baker"),
(16,"Harper", "Adams"),
(16,"Liliana", "Nelson"),
(16,"Evelyn", "Carter"),
(16,"Hazel", "Mitchell"),
(16,"Adalynn", "Perez"),
(16,"Rylee", "Roberts"),
(16,"Aaliyah", "Turner"),

(17,"Aurora", "Phillips"),
(17,"Brooklynn", "Campbell"),
(17,"Ellie", "Parker"),
(17,"Anna", "Evans"),
(17,"Ariana", "Edwards"),
(17,"Allison", "Collins"),
(17,"Genesis", "Stewart"),
(17,"Avery", "Sanchez"),
(17,"Scarlett", "Morris"),
(17,"Liam", "Green"),

(18,"Noah", "White"),
(18,"Ethan", "Harris"),
(18,"William", "Martin"),
(18,"James", "Thompson"),
(18,"Oliver", "Young"),
(18,"Benjamin", "Allen"),
(18,"Elijah", "King"),
(18,"Lucas", "Wright"),
(18,"Mason", "Scott"),
(18,"Alexander", "Jackson"),

(19,"Michael", "Lewis"),
(19,"Daniel", "Harris"),
(19,"Matthew", "Clark"),
(19,"Emma", "Martinez"),
(19,"Olivia", "Anderson"),
(19,"Ava", "Thomas"),
(19,"Isabella", "Moore"),
(19,"Sophia", "Martin"),
(19,"Mia", "Brown"),
(19,"Charlotte", "Davis"),

(20,"Amelia", "Miller"),
(20,"Harper", "Wilson"),
(20,"Evelyn", "Moore"),
(20,"Abigail", "Jones"),
(20,"Emily", "Smith"),
(20,"Elizabeth", "Johnson"),
(20,"Mila", "Williams"),
(20,"Ella", "Jones"),
(20,"Avery", "Davis"),
(20,"Sofia", "Wilson"),

(21,"Camila", "Anderson"),
(21,"Aria", "Thomas"),
(21,"Scarlett", "Jackson"),
(21,"Victoria", "Lewis"),
(21,"Madison", "Young"),
(21,"Luna", "Allen"),
(21,"Grace", "King"),
(21,"Chloe", "Wright"),
(21,"Penelope", "Scott"),
(21,"Riley", "Green"),

(22,"Layla", "Baker"),
(22,"Natalie", "Adams"),
(22,"Addison", "Nelson"),
(22,"Aubrey", "Carter"),
(22,"Brooklyn", "Mitchell"),
(22,"Ellie", "Perez"),
(22,"London", "Roberts"),
(22,"Hazel", "Turner"),
(22,"Nova", "Phillips"),
(22,"Aurora", "Campbell"),

(23,"Isabelle", "Parker"),
(23,"Adalynn", "Evans"),
(23,"Rylee", "Edwards"),
(23,"Everly", "Turner"),
(23,"Audrey", "Hall"),
(23,"Brielle", "Young"),
(23,"Arianna", "Allen"),
(23,"Kaylee", "King"),
(23,"Anna", "Wright"),
(23,"Caroline", "Scott"),

(24,"Natalie", "Green"),
(24,"Sarah", "Baker"),
(24,"Allison", "Adams"),
(24,"Savannah", "Nelson"),
(24,"Aaliyah", "Carter"),
(24,"Aubree", "Mitchell"),
(24,"Makayla", "Perez"),
(24,"Aurora", "Roberts"),
(24,"Bridgette", "Turner"),
(24,"Bella", "Phillips"),

(25,"Adalyn", "Campbell"),
(25,"Autumn", "Parker"),
(25,"Avery", "Evans"),
(25,"Brooklynn", "Edwards"),
(25,"Violet", "Turner"),
(25,"Ryleigh", "Hall"),
(25,"Claire", "Young"),
(25,"Eleanor", "Allen"),
(25,"Skylar", "King"),
(25,"Audrina", "Wright"),

(26,"Naomi", "Scott"),
(26,"Paisley", "Green"),
(26,"Aria", "Baker"),
(26,"Everleigh", "Adams"),
(26,"Adalynne", "Nelson"),
(26,"Avery", "Wagner"),
(26,"Riley", "Schneider"),
(26,"Aria", "Fischer"),
(26,"Evelyn", "Weber"),
(26,"Aubree", "Schulz"),

(27,"Adalynn", "Hoffmann"),
(27,"Eleanor", "Schäfer"),
(27,"Hazel", "Klein"),
(27,"Aurora", "Wolf"),
(27,"Bella", "Schubert"),
(27,"Lydia", "Peters"),
(27,"Scarlett", "Lang"),
(27,"Natalie", "Krause"),
(27,"Sophia", "Baier"),
(27,"Aaliyah", "Franke"),

(28,"Mila", "Konrad"),
(28,"Audrey", "Maier"),
(28,"Charlotte", "Bader"),
(28,"Brooklyn", "Stein"),
(28,"Violet", "Simons"),
(28,"Aurora", "Bartels"),
(28,"Avery", "Krause"),
(28,"Riley", "Hein"),
(28,"Aria", "Binder"),
(28,"Evelyn", "Voigt"),

(29,"Aubree", "Kramer"),
(29,"Adalynn", "Becker"),
(29,"Eleanor", "Horn"),
(29,"Hazel", "Arnold"),
(29,"Aurora", "Schreiber"),
(29,"Bella", "Pohl"),
(29,"Lydia", "Fuchs"),
(29,"Scarlett", "Götz"),
(29,"Natalie", "Schulze"),
(29,"Sophia", "Baumann"),

(30,"Aaliyah", "Kunz"),
(30,"Mila", "Herzog"),
(30,"Audrey", "Schumann"),
(30,"Charlotte", "Brunner"),
(30,"Brooklyn", "Windisch"),
(30,"Violet", "Schumacher"),
(30,"Aurora", "Rauch"),
(30,"Avery", "Hess"),
(30,"Riley", "Zimmermann"),
(30,"Aria", "Hofmann"),

(31,"Evelyn", "Friedrich"),
(31,"Aubree", "Weiß"),
(31,"Adalynn", "Schmitz"),
(31,"Eleanor", "Lang"),
(31,"Hazel", "Kühn"),
(31,"Aurora", "Herbst"),
(31,"Bella", "Winkler"),
(31,"L Lydia", "Roth"),
(31,"Scarlett", "Walter"),
(31,"Natalie", "Scholz"),

(32,"Sophia", "Ludwig"),
(32,"Aaliyah", "Bach"),
(32,"Mila", "Schreiner"),
(32,"Audrey", "Metzger"),
(32,"Charlotte", "Wagner"),
(32,"Brooklyn", "Riegel"),
(32,"Bella", "Müller"),
(32,"L Lydia", "Schumacher"),
(32,"Scarlett", "Röder"),
(32,"Natalie", "Stein");