drop table SPIEL;

CREATE TABLE SPIEL (
	SPIEL_ID	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	TEAM1_ID	int NOT NULL,
	TEAM2_ID	int NOT NULL,
	STADION_ID	int NOT NULL,
	BESUCHER	int,
	TOR_TEAM1	int,
	TOR_TEAM2	int,
	SCHIRI_ID	int NOT NULL,
	CONSTRAINT FK_TEAM2_ID FOREIGN KEY(TEAM2_ID) REFERENCES TEAM(TEAM_ID),
	CONSTRAINT FK_STADION_ID FOREIGN KEY(STADION_ID) REFERENCES STADION(STADION_ID),
	CONSTRAINT FK_TEAM1_ID FOREIGN KEY(TEAM1_ID) REFERENCES TEAM(TEAM_ID),
	CONSTRAINT FK_SCHIRI_ID FOREIGN KEY(SCHIRI_ID) REFERENCES SCHIRI(SCHIRI_ID)
)